

# the services to start
services:

  # development container
  roswork:

    # build from the local dockerfile
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=${USERNAME}
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}

    environment:
      - DISPLAY

    devices:
      - /dev/dri:/dev/dri
      - /dev/video0:/dev/video0

    # local machine mappings
    volumes:
      - ..:/workspace/rosWork
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    # command to keep the container running
    command: sleep infinity